### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by advdv** [timeglass/glass#1]
## 0.1
- [ ] Git checkout should start timer on entered branch
- [ ] Git checkout should stop on branch left
- [ ] File edits should prevent the timer from timing out
- [ ] Commits should register spend time in the commit
## 0.5
- [ ] restart timer when osx reboots
- [ ] allow for certain file patterns to be ignored (doesn't prevent timer from pauzing)
